services:
  emulerr-stalled-checker:
    build: .
    container_name: emulerr-stalled-checker
    environment:
      - TZ=Europe/Rome # set your timezone
      - CHECK_INTERVAL=10 # in minutes
      - EMULERR_HOST=http://10.0.0.100:3000
      - STALL_CHECKS=15 # number of checks before marking as stalled
      - STALL_DAYS=15 # days if the download has been never seen completed
      - RECENT_DOWNLOAD_GRACE_PERIOD=30 # how many minutes wait before checking if the download, apply only if the download is recent
      - DELETE_IF_UNMONITORED_SERIE=false # delete if the serie is not monitored
      - DELETE_IF_UNMONITORED_SEASON=false # delete if the season is not monitored
      - DELETE_IF_UNMONITORED_EPISODE=true # delete if the episode is not monitored
      - DELETE_IF_UNMONITORED_MOVIE=true # delete if the movie is not monitored
      - DELETE_IF_ONLY_ON_EMULERR=false # delete if the download is only on eMulerr but not inside *Arr, apply only for downloads with *Arr eMulerr category

      # Notification configuration using Apprise (supports 70+ services)
      # Recommended: Use APPRISE_URLS for maximum flexibility
      # Format examples:
      #   Pushover:  pover://user_key@app_token
      #   Telegram:  tgram://bot_token/chat_id
      #   Discord:   discord://webhook_id/webhook_token
      #   Multiple:  pover://key@token discord://webhook/id (space-separated)
      - APPRISE_URLS=pover://your_user_key@your_app_token

      # Legacy Pushover support (auto-converted to Apprise internally)
      # You can still use these instead of APPRISE_URLS if you prefer
      # - PUSHOVER_USER_KEY=your_pushover_user_key
      # - PUSHOVER_APP_TOKEN=your_pushover_app_token

      - LOG_LEVEL=info # or debug, warning, error, critical
      - LOG_TO_FILE=/path/to/logfile # optional, by default no log file is created, if set, the file will be created in the path specified, note volume must be mounted to the path
      - DRY_RUN=false
      - DOWNLOAD_CLIENT=emulerr # name of the download client inside *Arr
      - RADARR_HOST=http://10.0.0.100:7878
      - RADARR_API_KEY=***
      - RADARR_CATEGORY=radarr-eMulerr # Radarr category for eMulerr
      - SONARR_HOST=http://10.0.0.100:8989
      - SONARR_API_KEY=***
      - SONARR_CATEGORY=tv-sonarr-eMulerr # Sonarr category for eMulerr
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://10.0.0.100:3000"]
      interval: 1m
      timeout: 10s
      retries: 3
