name: Build AudioMediaChecker

on:
  push:
    branches: [ master ]
    paths:
      - 'AudioMediaChecker/**'
      - '.github/workflows/build-audiomedia-checker.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: docker/setup-buildx-action@v3
      
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - uses: docker/build-push-action@v5
        with:
          context: ./AudioMediaChecker
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/audiomedia-checker:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/audiomedia-checker:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
